image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      flutter pub get
    command: >
      flutter run --web-port=8080 --web-hostname=0.0.0.0
ports:
  - port: 8080
    onOpen: open-preview
vscode:
  extensions:
    - Dart-Code.flutter@3.12.2:8+9OCbCxNozE+NHjTY4Ubw==
    - Dart-Code.dart-code@3.12.2:U4I/KVVS4Adq5Ain/7bqhg==
    - msjsdiag.debugger-for-chrome@4.12.6:IdQBlCQEnixzHAOkHC36ew==